services:
  - type: web
    name: weeknd-tour
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MOLLIE_API_KEY
        value: live_pEjksv4HqkMCcb4vsEJgrcgSVR5TJy
      - key: WEBHOOK_URL
        value: https://weekend-7o0i.onrender.com/api/webhook
      - key: NODE_ENV
        value: production
